#!/bin/bash
# Day 17: Catalyst Optimizer Stages Verification Script
# Location: Day-17-Spark-SQL-Catalyst/scripts/verify-catalyst.sh

set -e

# Path configurations
DEMO_SCRIPT="/workspace/source/SparkSqlDemo.py"
OUTPUT_PLAN="/workspace/source/output/explain_plan.txt"

echo "=== 🔍 STEP 1: Running the Catalyst Optimizer Demo Script ==="
python3 "$DEMO_SCRIPT"

echo "=== 🔍 STEP 2: Verifying Extended Explain Plan Output ==="
if [ -f "$OUTPUT_PLAN" ]; then
  echo "✅ Success: Explain plan file exists at $OUTPUT_PLAN"
else
  echo "❌ Error: Explain plan file was not generated by the demo script."
  exit 1
fi

# Ensure all 4 plan phases of Catalyst exist in the output file
phases=("Parsed Logical Plan" "Analyzed Logical Plan" "Optimized Logical Plan" "Physical Plan")

for phase in "${phases[@]}"; do
  if grep -q "$phase" "$OUTPUT_PLAN"; then
    echo "✅ Success: Plan contains '$phase'."
  else
    echo "❌ Error: Plan is missing phase '$phase'."
    exit 1
  fi
done

echo "=== 🎉 Catalyst Optimizer Phase Lineages Verified Successfully! ==="
