[libdefaults]
    default_realm = HADOOP.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
    HADOOP.LOCAL = {
        kdc = kdc-server:88
        admin_server = kdc-server:749
    }

[domain_realm]
    .hadoop.local = HADOOP.LOCAL
    hadoop.local = HADOOP.LOCAL
    namenode = HADOOP.LOCAL
    datanode = HADOOP.LOCAL
    kms-server = HADOOP.LOCAL
