# configs/kafka-metrics.properties
# Kafka Metrics & JMX JVM Agent Configuration

metric.reporters=
kafka.metrics.polling.interval.secs=10

# JVM JMX Options to enable remote monitoring agent
# KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=5558:/opt/jmx_exporter/kafka.yml"
